# .github/workflows/build-windows-exe.yml

name: Build Windows Executable

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  workflow_dispatch: {} # Allow manual triggering from GitHub UI

jobs:
  build-windows-exe:
    runs-on: windows-latest # Use a Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or your desired Python version, e.g., '3.10', '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt # Install Flask, Flask-Cors
          pip install pyinstaller # Install PyInstaller separately
        shell: pwsh # Use PowerShell for improved script execution

      - name: Create static directory for frontend
        # Ensure the static directory exists, even if empty, for PyInstaller to find it
        # This step is mostly for robustness; ideally, backend/static already exists with your frontend files.
        run: |
          New-Item -ItemType Directory -Force -Path "backend/static"
        shell: pwsh # Use PowerShell for directory creation

      # NOTE: The 'Copy frontend files to static directory' step has been removed.
      # Please ensure your index.html, script.js, and style.css (or compiled Tailwind CSS)
      # are already committed directly into the 'backend/static/' folder in your repository.
      # Example: YourRepo/backend/static/index.html

      - name: Build Windows executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --add-data "backend/static;static" backend/app.py
        shell: pwsh # Use PowerShell for PyInstaller command
        working-directory: ${{ github.workspace }} # Run from the repository root

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PortableDNSManager-Windows-Executable
          path: dist/app.exe # Path to your generated .exe file
          retention-days: 7 # Keep the artifact for 7 days (optional)

      # NOTE: The 'Clean up build directories' step has been removed.
      # GitHub Actions automatically cleans up the runner's workspace after each job.
